### ISSUE TITLE
[story] As a user, I want to capture information from websites and commands, so that I can build my Knowledge Management System

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/protoHandler#3]
## User Story

As a user, I want to be able to capture and store information from various websites and command inputs, so that I can efficiently build and maintain a comprehensive Knowledge Management System (KMS).

## Acceptance Criteria

- The system should allow users to input URLs and extract relevant information from the specified websites.
- Users should be able to input commands that the system can execute to retrieve information.
- The captured information should be stored in an organized manner within the KMS.
- Users should be able to categorize and tag the captured information for easy retrieval.

## Definition of Done

A protocol handler sends a URI with information to the program, which is parsed, the individual fields are extracted, and an entry is made in the KMS using the relevant information.

## Tasks

- [ ] Accept a URI on the commandline, and pass it to a script for further processing
- [ ] Decide which script to run based on the protocol of the URI
- [ ] Parse the URI and fill out a template based on information in the fields
